### PR TITLE
Experimental

### PR DESCRIPTION
**Pull request by Uwajimaya**
Updated lighting files including volumetric taxi/landing, small lens flare for strobe/beacon.

### CODE REVIEW

**Comment by TheFrett** [comment]
Hey, thanks! Could you make it so that in systems.cfg only the [LIGHTS] section is changed. You are pushing some changes to the other sections that overwrite recent work.

Maybe update your fork from the upstream? https://digitaldrummerj.me/git-syncing-fork-with-original-repo/

**Comment by Uwajimaya** [comment]
Are you sure? I used your systems.cfg. I added my lights, but because there are more entries now, I had to resequence the entire lights section. No actual changes to anything other than external lights

**Comment by TheFrett** [comment]
Take a look at the diff. circuits 48 - 50 that I've added are missing in the systems.cfg that you committed...

**Comment by TheFrett** [comment]
Don't know what happenend. Your fork seems to be based on an up-to-date commit. But the systems.cfg that you placed in there is definitely older! See the last entries of the Electrical systems where I have three new circuits defined whereas these are missing in your file...

**Comment by Uwajimaya** [comment]
Ok, sorry about that. Do you want me to resubmit the systems.cfg or did you fix it on your end?

**Comment by TheFrett** [comment]
No problem! Would be the easiest way I think if you commit the correct file. Then I can complete the merge!

**Comment by Uwajimaya** [comment]
Alright, here it is. Seems correct now.

**Comment by TheFrett** [comment]
Looking good! Thanks! Will test the lights today!

**Comment by TheFrett** [comment]
One more question:

can I delete these:

image

**Comment by TheFrett** [comment]
Yeah they  dont seem to be referenced anymore

**Comment by Uwajimaya** [comment]
Correct, you can delete the old effects files (.._G36.fx)

**Pull request merged**
