### PR TITLE
Dev version: Updated EGT, Fuel and Power Scaling to match PoH. 

### PR DESCRIPTION
**Pull request by Matchrocket**
[engines.txt](https://github.com/TheFrett/msfs_g36_project/files/5248868/engines.txt)

Change Back to Default:
cylinder_displacement = 137.5; Cubic inches per cylinder
number_of_cylinders = 4 ; Number of cylinders

The combination of the above produces 550ci, which this plane is, and also produces correct trq values of ~600ft-lbs @ 2700 rpm. The previous CORRECT values of 92ci per cylinder and 6 cylinders produce up-to 45fl-lbs LESS torque, and really screws up the fuel flow and mixture settings. I tried playing with 99ci per cylinder, but the fuel flows were really wonky, and the flow scaler was HUGE at 1.25 … IN short, rabbit hole trying to balance everything out. Let’s just pretend this is right for now and move on.

fuel_flow_scalar = 1.05 ; ** Adjusted from default of 1.0 to match fuel flows at LoP @ Altitude on ISA
This pretty much makes fuel flows within one gph LoP @ 0 - 12000ft per PoH. I chose LoP because RoP is a Hot Mess due to mixture scaling.

egt_peak_temperature = 2100 ; ** adjusted from 1600 to fix EGT offsets.
This one was interesting, by default EGT values are absolute Zero (-273c or -460f) Per a suggestion from @MrTommymxr set it to 2100. This produced correct EGT Values at all ranges for this plane. REALLY close to what I’ve seen on the YouTubes. :wink: This also doesn’t tweak fuel flow at all, which is nice.

thrust_scalar = 1.2 ; THIS IS DEFAULT.

I adjusted this back to 1.2 from 1.3 as inflight speeds were to fast. @ 1.2 I am within 1 or 2 kts LoP on an ISA day 2k to 12k.

### CODE REVIEW

**Comment by TheFrett** [comment]
Awesome! 

But this is a request to merge dev-version into master. Please fork the dev-version and commit and push to that. Also I do not see your commit(s) of engines.cfg. Finally, did you test with dciskeys changes from pull request #23?

**Comment by Matchrocket** [comment]
I have no clue what I am doing with GitHub, first time using it.

Regarding other changes, no. How do I see those?

**Comment by Matchrocket** [comment]
Did this wrong I gues, closing.

**Comment by TheFrett** [comment]
Since you tested without these changes, could you also include flight_dynamics.cfg. then you will unfortunately overwrite his work, but it seems yours is superior! You can watch some guides on YouTube for GitHub! Useful especially if you want to do more work on MSFS. If not interested or if you don't have time, please send the files (so engine.cfg and the flight_model.cfg you tested this with) to me!

**Comment by Matchrocket** [comment]
The GitHub I see vs the instructions I found look totally different.  I can't view other forks, there is only one, mine.   I'll keep digging to see if I can figure it out. 

I am running 0.4 with my panel changes + the tweaks to the engine config below. I have no idea with dciskey changed as I can't see any of those anywhere. 

[engines.zip](https://github.com/TheFrett/msfs_g36_project/files/5250039/engines.zip)

**Comment by Matchrocket** [comment]
Okay;  I created a new fork and cloned the project.
https://github.com/Matchrocket/msfs_g36_project

This has all the files, including flight dynamics, + the changes I made.  I
"Think" I did it correctly, but it pushed to my branch only, I don't you if
you can see it or not.  Again, I am running 0.4 from the published version,
with my own engine.cfg changes

Regarding other people's changes, I still can't see those, only comments
and changes you've made.  https://www.youtube.com/watch?v=iv8rSLsi1xo was
my reference if it helps.

**Comment by TheFrett** [comment]
Hey. Almost there! Could you clone the dev-version. If you do so, you also automatically have the latest changes that we made. The master branch is released the Dev branch is where I merge pull requests. Once a lot of changes have been tested, I merge Dev with master and announce a new release. If you fork the Dev branch and commit your two cfg files, then you can make a pull request from your forked repo to the dev-version branch!

**Comment by Matchrocket** [comment]
https://github.com/TheFrett/msfs_g36_project/pull/27

From 0.5 Dev Version with my engine.cfg changes. Need to fly my engine.cfg
with all the other edits.

**Pull request closed without merging**
