### PR TITLE
Checklists Complete - needs testing

### PR DESCRIPTION
**Pull request by 50North4West**
**Completed Checklist!**

Sorry @TheFrett the only file changed is the Bonanza_G36_Checklist.xml - not sure how I brought over 18 files in this push

Following the Normal Procedures from POH Manual Bonanza-g36-POH-compressed.pdf 
Section 4 - Pages 159-206.

You can use the assisted checklist setting to get the copilot/pilot to read the checklist and check each item. 
 
**BUGS/ISSUES!!**

1. Copilot will not turn off avionics switch during the check all switches are off preflight action

1. Flood & Panel light switches do not show blue highlight
 
1. Unsure what the ID is for the A/C switch to add to the checklist

1. No EventID for the opening of the Cowl Flaps - copilot cannot open the flaps, need to investigate where the default actions live and create one

1. Fuel selector does not show blue highlight, completes when selecting any other selection rather than the fullest tank, also if you get copilot to do it, sometimes they turn off the fuel!
 
1. Before Taxi - Bus 2 Voltage check fails
 
1. Run-up - Bus 2 Voltage check fails

**TO DO**

1. Custom exterior views for the preflight check

1. Check Cruise fuel mixture setting, it should work out the best mixture

1. Complete a full test flight!

### CODE REVIEW

**Comment by TheFrett** [comment]
Did you update your fork with the latest dev-version before committing to it?

**Comment by TheFrett** [comment]
Would like to merge just the checklist. Possibly just send it to me.

**Comment by TheFrett** [comment]
nvm I will get it directly from your fork

**Comment by 50North4West** [comment]
Sorry! Yep, pulled down the latest files from the dev version. Need to watch a few YT videos to get my head around sharing and working with other repos

[Bonanza_G36_Checklist.zip](https://github.com/TheFrett/msfs_g36_project/files/5288889/Bonanza_G36_Checklist.zip)

**Comment by TheFrett** [comment]
I already merged it in the dev-version after getting the file directly from your dev-version fork. testing it now, looks really nice! Looks like you completed an immense task (3000 line, I hope a lot of copy+paste)

**Comment by 50North4West** [comment]
Once I got my head around the MSFS way of doing things thankfully a lot of the tasks/checks are able to be reproduced throughout. There are some definate bugs/issues to iron out but all there now. The cruise fuel control is an interesting one and once a few issues are sorted it should be able to get us to lean properly.

Just don't try to complete the takeoff checklist whilst taking off! It's easy to loose track of where you are and drive off the side of the runway!

**Pull request closed without merging**
