### PR TITLE
Dev version

### PR DESCRIPTION
**Pull request by Uwajimaya**
Updated lighting .fx files and systems.cfg lights section

### CODE REVIEW

**Comment by clompsy** [comment]
Please check, the systems.cfg references this effect:
`EffectFile:LIGHT_ASOBO_Taxi_G36`
But the file is called:
`bonanza-g36-improvement-project/effects/LIGHT_ASOBO_G36Taxi.fx`

I think the filename needs to be adjusted (append "_G36" instead of having G36 in the middle of the name).

**Comment by clompsy** [comment]
My commit was with the file 
`bonanza-g36-improvement-project/effects/LIGHT_ASOBO_Taxi_G36.fx`
already so you need to overwrite the file instead of creating a new one with a different name.

**Comment by Uwajimaya** [comment]
Ok, I will fix the naming error, but I'm afraid I have no idea what I am doing with the pull request. How do I overwrite something? What's the easiest for me to give you my files?

**Comment by clompsy** [comment]
Just make another commit, it should be added in this pull request automatically. :)

**Comment by Uwajimaya** [comment]
Ok, deleted file with typo, added file with correct name. Did that work? Apologies for the mess

**Comment by clompsy** [comment]
All fine now, thanks! No mess to apologize for :) 
Don't have time today to try it out, but the files look fine.

**Comment by TheFrett** [comment]
Great, thank you both!

**Comment by Uwajimaya** [comment]
Hey guys, heads up - today's patch made changes to the manifest.json . Without an update from  us mod makers, no current mods will show up. Easiest way to fix it is to replace your current manifest.json with the one from the official package of the G36.

**Pull request merged**
