### PR TITLE
Take Off Roll Yaw Rate sensitivity improvement.

### PR DESCRIPTION
**Pull request by Matchrocket**
It bothered me from day one how stupid sensitive the rudder is on takeoff roll. I found a way to tune this based on airspeed and not impact the ground turning radius at taxi speeds.

yaw_moment_yaw_rate_mach_table = 0.0449:-1.5, 0.0599:-1.25, 0.0749:-1, 0.0899:-0.50, 0.1059:-0.25, 0.12:0 ****30 40 50 60 70 80 kts, default is 0:0

This table adjusted the rate of yaw change at airspeeds up-to rotate. This allows for much more control to maintain centerline during take-off and landing.

I also tweaked the autopilot max roll and max pitch angles. From 25/25 to 20/15. I found it would roll to steep and stall if you engage at lower airspeeds, and the max pitch was 25 which would cause crazy nose dives or stalls trying to adjust when you engage auto-pilot with large deltas to current vs desired alts.

### CODE REVIEW

**Comment by TheFrett** [comment]
Hi,

Dciskey and Exp232 have tuned the fm with zero_lift_drag_scalar 0.32, so I will revert that change.

**Comment by TheFrett** [comment]
Nvm it was 0.33 actually that they worked with

**Comment by TheFrett** [comment]
One thing though. Can you still keep her on the runway at a little over max demonstrated crosswind? Or is there a lack of rudder authority now?

**Comment by Matchrocket** [comment]
Yes, Was able to hold @ 20kts which is above the max demonstrated crosswind. This change DOES NOT impact the max deflection, just modifies the rate of change @ that deflection for a given airspeed. poor man's PID in that regard.

**Pull request merged**
