### PR TITLE
Update to reflect changes made in WU4 to WT-G1000 loading

### PR DESCRIPTION
**Pull request by 50North4West**
As per message in WT Discord https://packages.workingtitle.aero/g1000/2021/04/14/g1000-release-v0.3.5.html I've removed the WTEngineDisplay.xml and moved the code into the Panel.xml. Updated the readme to show WT-G1000 0.3.5 is required.

### CODE REVIEW

**Comment by TheFrett** [comment]
I don't have time to test it myself. Is everything working as required?

e.g. all the custom indications from XMLVARS (the smoothened indications for battery and load indications, fuel flow, etc?)

**Comment by 50North4West** [comment]
Hey,

Yep all working as previously, the only change has been moving the code. I have seen one thing and I can't remember whether it happened before the WU4 update was that the Pitot Heat warning is displayed if Pitot Heat off.

**Review by nikilase — COMMENTED** [review]
Why were the announciators like FUEL QTY LO or BUS2 VOLT LO removed from the panel.xml?
I actually see, that I made a mistake in my panel.xml, I don't know if you used mine or did it yourself. 

I used the panel.xml provided by WorkingTitle, not the one provided by this mod. Therefore I missed a whole lot of announciators and maybe some other stuff.

**Comment by 50North4West** [comment]
@nikilase Good spot! I did the same! I'm about to upload a new pull request, that will teach me for having multiple copies!

**Comment by 50North4West** [comment]
@nikilase I've made the changes to the Master branch, do you want to download and test?

**Comment by nikilase** [comment]
@50North4West was just about to diff them and then do a test flight.

**Pull request merged**
