### PR TITLE
Tweak 2300RPM and flap drag

### PR DESCRIPTION
**Pull request by dciskey**
Reduced efficiency at 2300RPM and increased flap drag. A new, correct pull request (sorry for being a newb).

### CODE REVIEW

**Comment by TheFrett** [comment]
Did you test approach settings with the new flap drag (Known manifold, fpm and speed combinations)?

**Comment by dciskey** [comment]
Yes, I couldn't find any baselines in the forum thread, but I compared with numbers discussed here: https://www.pilotsofamerica.com/community/threads/anyone-have-performance-numbers-for-a-bonanza-a36.26874/ and with this video: https://www.youtube.com/watch?v=YzeWWnbwBdo&t=124s (the light is faint but the video starts with flaps at approach). Did several 3 degree ILS approaches and found I had to drop power below the discussed settings unless I added the little bit of extra flap drag.

**Comment by TheFrett** [comment]
Could you check against:

https://forums.flightsimulator.com/t/g36-fixes-and-improvements-update-12-09/216094/42

and

https://forums.flightsimulator.com/t/g36-fixes-and-improvements-update-12-09/216094/213

Both kind of buried posts in the main thread. Both posted by G36 pilots btw.

**Comment by dciskey** [comment]
Oh, great, I totally missed those. I'll check and get back to you!

**Comment by TheFrett** [comment]
Also while you're at it: could you check idle RPM? It is too high. It may be tuned by the engine friction table. I can do it too, let me know! I'm busy with the electrical system...

**Comment by dciskey** [comment]
Yep, I can take a look at that over the next couple of days. Looks like approach speeds with flaps either approach or full down are good, but the speed down low at 20" and 2300RPM is a bit high when clean. Will be tricky to adjust without hurting cruise speeds, but I'll keep working on it. In the meantime I think this change to the flap drag is an okay interim solution to keep approach speeds down.

**Comment by dciskey** [comment]
Uploaded some new changes today. I think they're nearly ready for prime time. Speeds at 20" and 2300RPM are a bit lower at 2000ft. Cowl flaps open helps bring it under control. Didn't have time to fly any approaches; would love to hear back if anybody is able to, and I'll try to do a few tomorrow.

**Comment by Exp232** [comment]
I can try an approach now, I'll get back to you.

**Comment by Exp232** [comment]
image


Here's my result. Mind you it's only a snapshot of the full approach, but I from what I could tell the approach flaps still need a little more drag (I was pulling 123 KIAS in approach config, should be around 110) as well as the gear. I also did some climb testing and it's damn close. Within 5-10%, although performance was consistently above POH numbers, But wow, this has come a long way! TLDR; Reduce performance ever so slightly, increase drag on flaps and gear a bit as well, and you've got yourself a winner 🥇 

2000 | 11 | 100 | 1210 | 1220 | 99.18%
4000 | 7 | 100 | 1045 | 960 | 108.85%
6000 | 3 | 100 | 910 | 850 | 107.06%
8000 | 0 | 100 | 775 | 730 | 106.16%
10000 | -4 | 100 | 640 | 600 | 106.67%
12000 | -8 | 100 | 505 | 480 | 105.21%
14000 | -12 | 100 | 360 | 360 | 100.00%
16000 | -16 | 100 | 220 | 240 | 91.67%

**Comment by TheFrett** [comment]
3100 lbs is really low? I have never seen that in charts. Always 3400 or 3650. For climbing (I assume you used 3650lbs for climbing  did you also use automixture? Because you can never reach the same power level with manual mixture apparently.

@dciskey please do not use the flap_induced_drag_scalar, but the drag coefficients of the individual flap settings. Best set the scalar to 1 and adjust the numbers 0.21 and 0.65 below. 0.65 appears to be good, 0.21 needs to be raised as I understand.

flaps-position.0 = 0, -1, 0
flaps-position.1 = 12, 154, 0.21
flaps-position.2 = 30, 124, 0.65

**Comment by Exp232** [comment]
> 3100 lbs is really low? I have never seen that in charts. Always 3400 or 3650. For climbing (I assume you used 3650lbs for climbing did you also use automixture? Because you can never reach the same power level with manual mixture apparently.

Is it? Empty weight 2600, two souls on board, and a generous two hours of fuel worked out to 3100 for me. Is my math wrong?

Yes, all climb performance tests followed regular convention, all the way down to unlimited fuel to maintain that perfect 3650. Automixture as well :)

**Comment by Exp232** [comment]
Out of curiosity I did the same approach at MTOW. Maybe, MAYBE a 1 knot difference. So I guess weight is a nonissue as it were :)

**Comment by Exp232** [comment]
I've got no data to support how well the drag on full flaps is performing currently. I'll see about performing some stalls and see where that gets me? Can't think of any other way to test full flaps with hard numbers, honestly.

**Comment by Exp232** [comment]
Also thought I'd point out the POH landing roll account for weight down to 2,800 lbs. Which is the aircraft, approx. 30 minutes of fuel, and a 158 lb. pilot haha

**Comment by TheFrett** [comment]
Ah if it makes that little difference then there is no problem :). It makes sense to include a wide range of weights for the landing roll,  since the effect of weight is far more significant on the roll length than say on the cruise speeds or approach speeds as you pointed out.

**Comment by dciskey** [comment]
@TheFrett Cool, I'll work on it some this morning.

@Exp232 I'm ok if it climbs a few percentage points better than the POH with automixture on; AM puts out more power than is possible with any manual mixture setting, and I assume most of us won't be using AM outside of testing. For cruise tests I now turn it off and lean to 20 degrees rich of peak, now that I know how simvars works and can see the EGT number. Matchrocket did some good work on the engine config, though it's slightly more accurate when lean of peak.

**Comment by Exp232** [comment]
Sounds good to me :) Happy to test accuracy with AM off as well, but I think we're well within the ballpark here. 

Did some stall testing, numbers with full flaps was spot on.

**Comment by dciskey** [comment]
I've done some further tweaking and testing and I think it's pretty darn close. Just a couple of notes. Performance on approach is most accurate with 100% mixture. This is not the best power setting for landings in the sea level to 1,000ft range; that's about 90%. But I figure the checklist that's being built will instruct pilots to go full rich before approach. Speeds are maybe 2-3kts too high on approach with cowl flaps closed; we'll have to get some input from real pilots but I'd assume you'd approach with them at some sort of open position to give better cooling if you have to do a go around. Cowl flaps 50% gives approach speeds that are right on. Here I am with cowl flaps closed and 91% mix:
Microsoft Flight Simulator 9_27_2020 8_38_25 AM

Here is the current state of climb and cruise. Again, climb being slightly too good with AM on is fine with me; AM gives a little extra power.
Screenshot (3)
I didn't do thorough testing LOP but the numbers there are slightly closer to book, since that's where Matchrocket did their optimizing. I'm not sure if we can get both ROP and LOP right on.

Anyway, I'm pretty happy with where this is at and I hope it's up to snuff!

**Comment by TheFrett** [comment]
Merged. We still need to tweak idle RPM for a release though. Will you look at it or shall I do it?

**Comment by dciskey** [comment]
I forgot to mention it but I fixed idle RPM. Brought the friction back to 1
and it idles about 710-720, which is about right from what I’ve read.

**Comment by TheFrett** [comment]
Great!

**Pull request merged**
