### PR TITLE
Update engines.cfg

### PR DESCRIPTION
**Pull request by mrtommymxr**
Changed spring back behaviour. Min_gov_rpm increased to 1500 to reduce sensitivity

### CODE REVIEW

**Comment by mrtommymxr** [comment]
I hope i did this right :)

**Comment by TheFrett** [comment]
The PR is good! However, you can commit changes directly to your forked experimental branch! No need to make a new branch (patch-1, patch-2) everytime you commit a change. If I make any changes, you can update your fork by following these instructions: https://digitaldrummerj.me/git-syncing-fork-with-original-repo/

Could you explain what these adjusted numbers do? I have no idea...

**Comment by mrtommymxr** [comment]
Im using the browser for everything. 
The minimum prop RPM is self explanatory, This lowers the sensitivity of the propcontrol axis to make adjustments finer. 
recip_stop_arc_restitution: 0.0 removes the spring back behaviour when turning the engine off. When gliding engine out it will bounce back and forth in a really, ugly, manner

**Comment by TheFrett** [comment]
I suppose you can do the same things in the browser / GUI. 

Can you still feather the prop as much as before?

**Comment by mrtommymxr** [comment]
true ,forgot about that. no, its stays at fine pitch :/

**Pull request closed without merging**
