### PR TITLE
Compatibility update for MSFS 1.18.13.0 (SimUpdate 5)

### PR DESCRIPTION
**Pull request by clompsy**
Updated the interior model definition by merging changes done in the base Asobo version to the modded file, keeping all modded parts intact.

### CODE REVIEW

**Comment by Biggsz** [comment]
Hello, I tested this and found that the throttle man pressure indicator shows "NaN" for me.

image

**Comment by clompsy** [comment]
@Biggsz Please be more precise. 
Do you see this in the MFD or the PFD? 
Are you sure you're using the G1000 v0.4.0 mod and you don't have the G1000 NXi mod installed since these are incompatible yet?
The only case I see the manifold pressure showing NaN is when starting Cold&Dark and turning on the batteries only (MFD stays black), then in the PFD the MP and the FuelFlow show NaN for me.

Not sure if that was the case before this update and due to lack of information I'm not sure if you're reporting the same issue or something else.
I could not get the MFD to show NaN when using only this version and G1000 v0.4.0.

**Comment by clompsy** [comment]
I debugged the PFD display, it seems like WT G1000 v0.4.0 has an issue with the TextIncrement value causing the NaN in the PFD.
I removed this parameter for the main gauge of manifold pressure and fuel flow since the default display in the MFD (one decimal) is the default.
PFD has a different default for manifold pressure resulting in the value shown without decimals. But that's still better than NaN.

Also added the change that Asobo did to the base aircraft, a new toggle in the flight_mode.cfg. section FLIGHT_MODEL to set modern_fm_only = 1.
Probably this avoid issues with people flying in legacy flight model which is a useful setting for this mod as well.

**Comment by Biggsz** [comment]
Hello,

My bad, I was with the stock G1000 as I forgot to put back the WT G1000 mod in my community folder. Now it works, thanks for your time.

**Comment by clompsy** [comment]
Merged the changes from Asobo to ModelBehaviorDefs/Asobo/Exterior.xml since this mod overrides this very global file.
We should think if the propeller animation switch of RPM (the only reason it is part of the mod) is really worth the risk of breaking other aircraft.
I'd suggest to omit this file in the mod and use the default animations instead.

**Pull request merged**
