### PR TITLE
Update AP System

### PR DESCRIPTION
**Pull request by Exp232**
Added min/max IAS_ref speeds for FLC mode. Thanks to Jonasbeaver

### CODE REVIEW

**Comment by TheFrett** [comment]
Hi, thanks! Just saw the forum discussion too.

Make sure you have pulled the latest changes to your forked repo. Not a big deal this time.

https://digitaldrummerj.me/git-syncing-fork-with-original-repo/

**Comment by Exp232** [comment]
Thank for the link, literally my first PR. Thought I had it all right, guess not :P

**Comment by TheFrett** [comment]
I only made a small change to the readme since you forked the repo, so that was easy to merge. Good first PR!

**Comment by jonasbeaver** [comment]
he did better than I did, good work!

**Pull request merged**
