### PR TITLE
Cruise/Climb tweaks

### PR DESCRIPTION
**Pull request by dciskey**
I've done some work to match the POH even closer, especially when it comes to fuel burn. Files are in the zip (I sure hope that's the right way to do this). Test results are below. I wonder if increase some drag coefficient or scalar would reduce performance at low altitude without hurting high altitude performance. It'll be several days before I'm able to do more work so I figured I'd upload what I have so far.
G36tweaks

[tweaks.zip](https://github.com/TheFrett/msfs_g36_project/files/5235758/tweaks.zip)

### CODE REVIEW

**Comment by jonasbeaver** [comment]
Hey Dciskey, per chance are you an fseconomy player? I'm pretty sure I bought the da40ng you flew a month ago in Minnesota. Lol

**Comment by dciskey** [comment]
> Hey Dciskey, per chance are you an fseconomy player? I'm pretty sure I bought the da40ng you flew a month ago in Minnesota. Lol

Yes, I believe I did fly a DA40 about a month ago in Minnesota!

**Comment by jonasbeaver** [comment]
Lol! I've been tweaking the da40's flight model / engine, using that plane! 
There isn't the kind of collaboration that's happening here with the G36 for the DA40ng, but I have a little time in the NG (nothing like the 2000 g36 hours I have) so I thought I'd play around with the flight model / engines.cfg while i've been flying it real time to Europe (had to wait out the last 4 days due to weather/sleep schedule)
 I'm looking forward to having a tailwind in the North Atlantic for first time! I'm new to fse, it's totally a neat way to fly

**Comment by dciskey** [comment]
> Lol! I've been tweaking the da40's flight model / engine, using that plane!
> There isn't the kind of collaboration that's happening here with the G36 for the DA40ng, but I have a little time in the NG (nothing like the 2000 g36 hours I have) so I thought I'd play around with the flight model / engines.cfg while i've been flying it real time to Europe (had to wait out the last 4 days due to weather/sleep schedule)
> I'm looking forward to having a tailwind in the North Atlantic for first time! I'm new to fse, it's totally a neat way to fly

Nice! I've been playing FSE since March. Most of my interest in the G36 comes from wanting to use it in FSE; I have the Cessna 210 in XP11 and to me five seats makes for solid income without getting into the big planes. I'm curious to know your thoughts on the MSFS DA40NG; it seemed a little slow from what I've read but I have no experience. Never been up in a Bonanza either but there are lots of Youtubers who fly it at least.

**Comment by jonasbeaver** [comment]
The DA40 was as terribly underpowered as the bonanza, there were some hilariously bad things, for example its placarded for the long range tanks, it was only sold in the states with long range tanks, but for some reason the fuel quantity was set up for for 28g instead of 40g. Digging deeper it got worse: engine compression ratios were way off, the plane sank WAY more than its real life counterpart, the engine is fadec with a prop that should be at 2100rpm almost all the time but at full power boost to 2300rpm, then return to 2100rpm by 92% load.

I could really use a hand with it if you are up for a challenge.

**Comment by jonasbeaver** [comment]
http://www.mediafire.com/file/3h6ycivmb9zsnqc/asobo-aircraft-da40-ng_edited_files_jwb.zip/file
that's as far as I got. Book #s are close, but to get it up to speed it has too little low end drag. It should float, so this actually helped, but I need the lift to stay up and the low power prop drag to increase by maybe 20%, its where I got stuck. Try a no flap landing, crossing the fence at 100kts you can float all the way down a 3000ft runway at idle.

**Comment by dciskey** [comment]
I’ll try and take a look when I can; life has been a little weird the last few weeks. My expertise is limited to tweaking findings and running tests so eventually the G36 won’t need me. :)

As an aside, does anybody have a link to a good “how to Github” guide, either written or video? I’m not sure I did this pull request properly and I don’t really know where to go from here.

**Comment by TheFrett** [comment]
You are trying to merge the dev-version into master. Also I don't see any of your own edits.

I use git from the command line. Search for 'git command line' on youtube. There is enough.

**Comment by TheFrett** [comment]
If you want I can push the changes to the repository if you post the file! If you want to make more contributions it would be useful to learn the pull request (if every one sends files it will be a nightmare to track versions and merge changes).

Here is a good one:

https://www.youtube.com/watch?v=FQsBmnZvBdc

**Comment by TheFrett** [comment]
You may want to watch the tutorials before that. If you don't have time (or don't want to spend the time to learn something that you may not use that much) just send the files ;)

**Comment by dciskey** [comment]
I'll check some tutorials on my lunch break and after work and see if I can fix this pull request this evening. I do want to learn the proper way to go about it.

**Comment by dciskey** [comment]
Ok, closing this because I believe I've figured out how to do it correctly.

**Pull request closed without merging**
